select * from customer limit 20;
--revenue generated by male Vs female
select gender,sum(purchase_amount) as revenue from customer group by gender;
--customer used a discount but still spent more than average purchase amount
select customer_id,purchase_amount from customer
where discount_applied='Yes' and purchase_amount>=(select avg(purchase_amount)from customer);
---top 5 products with highest  average review rating
select item_purchased,round(avg(review_rating::numeric),2) as "Average Product Rating" from
customer
group by item_purchased
order by avg(review_rating) desc
limit 5;
---average purchase amounts between standard and express shipping
select shipping_type,round(avg(purchase_amount),2) 
from customer where shipping_type in ('Standard','Express')
group by shipping_type;
--comparision between subscribed customers and non subscribed
select subscription_status,count(customer_id) as total_customers,
round(avg(purchase_amount),2) as avg_spend,
round(avg(purchase_amount),2) as total_revenue 
from customer
group by subscription_status
order by total_revenue,avg_spend desc;
---top 5 products with highest percentage of purchases with discount applied
select item_purchased,
round(100*sum(case when discount_applied='Yes' then 1 else 0 end)/count(*),2) as discount_rate
from customer 
group by item_purchased
order by discount_rate desc
limit 5;
---segmenting customers into new,returning,loyal based on 
---their total number of previous purchases and their count
with customer_type as(
select customer_id,previous_purchases,
case 
when previous_purchases=1 then 'New'
when previous_purchases between 2 and 10 then 'Returning'
else 'Loyal' end as customer_segment from customer
)
select customer_segment,count(*) as "Number of customers" from customer_type 
group by customer_segment;
---selecting top 3 products from each category
with item_counts as (
select category,item_purchased,count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) desc) as item_rank
from customer group by category,item_purchased)
select item_rank,category,item_purchased,total_orders from item_counts where item_rank<=3;
)
---customers who are repeat buyers (more than 5 previous) also likely to sibsrcobe
select subscription_status,
count(customer_id) as repeat_buyers
from customer where previous_purchases >5
group by subscription_status;
---revenue by age group
select age_group,
sum(purchase_amount) as total_revenue
from customer 
group by age_group
order by total_revenue desc;